?start: program 

// a program is a block
program: block

// a block is zero or more statements
block: statement*


// statement
?statement: variable_declaration ";"
    | assignment ";"
    | if_statement
    | while_statement
    | for_statement


// datatype
datatype: "int" -> int_type
    | "bool" -> bool_type


// variable declaration
variable_declaration: datatype NAME -> var_declaration
    | datatype NAME "=" expression -> var_declaration_with_value


// assignment
assignment: NAME "=" expression


// if statement
if_statement: "if" "(" expression ")" "{" block "}" -> if_only_statement 
    | "if" "(" expression ")" "{" block "}" "else" "{" block "}" -> if_and_else_statement


// while loop
while_statement: "while" "(" expression ")" "{" block "}"


// for loop
for_statement: "for" "(" assignment ";" expression ";" assignment ")" "{" block "}"


// arithemtic and logical expression
?expression: logical_or


// logical or
?logical_or: logical_and
    | logical_or "||" logical_and -> logical_or


// logical and
?logical_and: bitwise_or
        | logical_and "&&" bitwise_or -> logical_and


// bitwise OR
?bitwise_or: bitwise_xor
        | bitwise_or "|" bitwise_xor -> bitwise_or 


// bitwise XOR
?bitwise_xor: bitwise_and
        | bitwise_xor "^" bitwise_and -> bitwise_xor


// bitwise AND
?bitwise_and: equality
        | bitwise_and "&" equality -> bitwise_and


// equality expression (==, != operators)
?equality: relational "==" sum -> equal_to
        | relational "!=" sum-> not_equal_to
        | relational


// relational expression (>, <, >=, <=, ==, != operators)
?relational: shift
    | shift ">" shift -> greater_than
    | shift "<" shift -> less_than
    | shift ">=" shift -> greater_than_equal
    | shift "<=" shift -> less_than_equal

// bitwise operators (<<, >>)
?shift: sum
    | shift "<<" sum -> bitwise_left_shift
    | shift ">>" sum -> bitwise_right_shift


// sum (plus, minus operators)
?sum: product
    | sum "+" product   -> add
    | sum "-" product   -> sub


// product (times, divides operators)
?product: unary 
    | product "*" unary  -> mul
    | product "/" unary  -> div


// unary (bitwise NOT, logical NOT, negation)
?unary: "!" unary -> logical_not 
    | "~" unary -> bitwise_not
    | "-" unary -> neg
    | atom


// atom (number, variable, bracketed expression)
?atom: NUMBER -> number
    | "true" -> true
    | "false" -> false
    | NAME -> var
    | "(" expression ")"


%import common.CNAME -> NAME
%import common.NUMBER
%import common.WS

%ignore WS