?start: block

// a block is zero or more statements
?block: statement*


// statement
?statement: variable_declaration ";"
    | assignment ";"
    | if_statement
    | while_statement
    | for_statement


// datatype
?datatype: "int" -> int_type
    | "bool" -> bool_type


// variable declaration
variable_declaration: datatype NAME -> var_declaration
    | datatype NAME "=" expression -> var_declaration_with_value


// assignment
?assignment: NAME "=" expression


// if statement
?if_statement: "if" "(" condition ")" "{" block "}" -> if_only_statement 
    | "if" "(" condition ")" "{" block "}" "else" "{" block "}" -> if_and_else_statement


// while loop
?while_statement: "while" "(" condition ")" "{" block "}"


// for loop
?for_statement: "for" "(" (variable_declaration | assignment) ";" condition ";" assignment ")" "{" block "}"


// condition
?condition: expression
    | expression ">" expression -> greater_than
    | expression "<" expression -> less_than
    | expression "==" expression -> equal_to
    | expression "!=" expression -> not_equal_to
    | expression ">=" expression -> greater_than_equal
    | expression "<=" expression -> less_than_equal


// expression
?expression: product
    | expression "+" product   -> add
    | expression "-" product   -> sub


// product
?product: atom
    | product "*" atom  -> mul
    | product "/" atom  -> div


// atom
?atom: NUMBER           -> number
        | "-" atom         -> neg
        | NAME             -> var
        | "(" expression ")"


%import common.CNAME -> NAME
%import common.NUMBER
%import common.WS

%ignore WS